title: Spring Certified Professional Exam Preparation
theme: jekyll-theme-primer

domain: squidxtv.me
url: https://squidxtv.me
baseurl: "/Spring-Certified-Professional-Exam-Preparation"

relative_links:
  enabled: true
  collections: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
