title: Spring Certified Professional Exam Preparation
theme: jekyll-theme-primer
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
baseurl: "/spring-certified-professional"
