title: Spring Certified Professional Exam Preparation
theme: jekyll-theme-primer
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
url: https://squidxtv.me
baseurl: /spring-certified-professional
include:
  - README.md
  - "1. Spring Core"
  - "2. Data Management"
  - "3. Spring MVC"
  - "4. Testing"
  - "5. Security"
  - "6. Spring Boot"
